export const launchpadFactoryAbi = [
  {
    type: 'function',
    name: 'createToken',
    stateMutability: 'payable',
    inputs: [
      { name: 'name', type: 'string' },
      { name: 'symbol', type: 'string' },
      { name: 'normalizedNameHash', type: 'bytes32' },
      { name: 'normalizedSymbolHash', type: 'bytes32' },
      { name: 'totalSupply', type: 'uint256' },
      { name: 'graduationTarget', type: 'uint256' },
      { name: 'antiBotEnabled', type: 'bool' },
      { name: 'antiBotDurationSeconds', type: 'uint64' },
      { name: 'antiBotBaseLimitWei', type: 'uint256' },
      { name: 'vvsRouter', type: 'address' },
      { name: 'wrappedNative', type: 'address' },
      { name: 'lpBeneficiary', type: 'address' },
      { name: 'lpLockDurationSeconds', type: 'uint64' },
    ],
    outputs: [{ name: 'token', type: 'address' }],
  },
  {
    type: 'function',
    name: 'buy',
    stateMutability: 'payable',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'sell',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'token', type: 'address' }, { name: 'tokensIn', type: 'uint256' }, { name: 'minCroOut', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'quoteBuyTokens',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }, { name: 'croIn', type: 'uint256' }],
    outputs: [{ name: 'tokensOut', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'quoteSellCro',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }, { name: 'tokensIn', type: 'uint256' }],
    outputs: [{ name: 'croOut', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'launchStateByToken',
    stateMutability: 'view',
    inputs: [{ name: 'token', type: 'address' }],
    outputs: [
      { name: 'reserveRaisedWei', type: 'uint256' },
      { name: 'graduated', type: 'bool' },
      { name: 'pair', type: 'address' },
      { name: 'lpVault', type: 'address' },
      { name: 'liquidity', type: 'uint256' },
      { name: 'lpUnlocksAt', type: 'uint256' },
      { name: 'tokensSoldWei', type: 'uint256' },
    ],
  },
  { type: 'event', name: 'TokenCreated', inputs: [
    { name: 'token', type: 'address', indexed: true },
    { name: 'creator', type: 'address', indexed: true },
    { name: 'name', type: 'string', indexed: false },
    { name: 'symbol', type: 'string', indexed: false },
    { name: 'normalizedNameHash', type: 'bytes32', indexed: true },
    { name: 'normalizedSymbolHash', type: 'bytes32', indexed: false },
    { name: 'totalSupply', type: 'uint256', indexed: false },
    { name: 'graduationTargetWei', type: 'uint256', indexed: false },
    { name: 'antiBotEnabled', type: 'bool', indexed: false },
    { name: 'vvsRouter', type: 'address', indexed: false },
    { name: 'wrappedNative', type: 'address', indexed: false },
    { name: 'lpBeneficiary', type: 'address', indexed: false },
    { name: 'lpLockDurationSeconds', type: 'uint64', indexed: false },
  ] },
  { type: 'event', name: 'TokenBought', inputs: [{ name: 'token', type: 'address', indexed: true }, { name: 'buyer', type: 'address', indexed: true }, { name: 'croIn', type: 'uint256', indexed: false }, { name: 'tokensOut', type: 'uint256', indexed: false }, { name: 'reserveRaisedWei', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'TokenSold', inputs: [{ name: 'token', type: 'address', indexed: true }, { name: 'seller', type: 'address', indexed: true }, { name: 'tokensIn', type: 'uint256', indexed: false }, { name: 'croOut', type: 'uint256', indexed: false }, { name: 'reserveRaisedWei', type: 'uint256', indexed: false }] },
  { type: 'event', name: 'TokenGraduated', inputs: [
    { name: 'token', type: 'address', indexed: true },
    { name: 'creator', type: 'address', indexed: true },
    { name: 'vvsRouter', type: 'address', indexed: true },
    { name: 'pair', type: 'address', indexed: false },
    { name: 'lpVault', type: 'address', indexed: false },
    { name: 'reserveRaisedWei', type: 'uint256', indexed: false },
    { name: 'tokenLiquidity', type: 'uint256', indexed: false },
    { name: 'liquidity', type: 'uint256', indexed: false },
    { name: 'lpUnlocksAt', type: 'uint256', indexed: false },
  ] },
] as const;

export const launchTokenAbi = [
  { type: 'function', name: 'approve', stateMutability: 'nonpayable', inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }], outputs: [{ name: '', type: 'bool' }] },
  { type: 'function', name: 'balanceOf', stateMutability: 'view', inputs: [{ name: 'account', type: 'address' }], outputs: [{ name: '', type: 'uint256' }] },
] as const;

export const lpVaultAbi = [
  { type: 'event', name: 'LpDeposited', inputs: [{ name: 'lpToken', type: 'address', indexed: true }, { name: 'beneficiary', type: 'address', indexed: true }, { name: 'amount', type: 'uint256', indexed: false }, { name: 'unlocksAt', type: 'uint256', indexed: false }] },
] as const;
